#
# Jekyll configuration
#
#exclude: ["vendor"]

markdown: kramdown

encoding: utf-8

gems:      ["jekyll-gist"]

collections:
    ios:
            output: true
            permalink: /:path/index:output_ext
    kits:
            output: true
            permalink: /:path/index:output_ext
    xcodes:
            output: true
            permalink: /:path/index:output_ext
    features:
            output: true
            permalink: /:path/index:output_ext
    externals:
            output: true
            permalink: /:path/index:output_ext
    cvs:
            output: true
    devices:
            output: true
            permalink: /:path/index:output_ext
    languages:
            output: true
            permalink: /:path/index:output_ext
    functional:
            output: true
            permalink: /functional/:path/index:output_ext

versions:
- WatchOS
- iOS2
- iOS3
- iOS4
- iOS5
- iOS6
- iOS7
- iOS8
- iOS9
- iOS10

currentVersions:
- iOS10

languageFeatures:
- TypeSafety
- TypeInference
- Immutability
- StatelessProgramming
- PureFunction
- FirstClassFunction
- HigherOrderFunction
- PatternMatching
