#
# Jekyll configuration
#
#exclude: ["vendor"]

markdown: kramdown

encoding: utf-8

collections:
    ios:
            output: true
            permalink: /:path/index:output_ext
    kits:
            output: true
            permalink: /:path/index:output_ext
    xcodes:
            output: true
            permalink: /:path/index:output_ext
    features:
            output: true
            permalink: /:path/index:output_ext
    externals:
            output: true
            permalink: /:path/index:output_ext
    cvs:
            output: true

versions:
- iOS2
- iOS3
- iOS4
- iOS5
- iOS6
- iOS7
- iOS8